### ISSUE TITLE
"limit" option

### ISSUE THREAD

**Issue by ludobrands** [rankactive/cassandra-fdw#2]
Hi,

I noticed the "limit" option in the source code which seems to fit our requirement to limit the risk of badly written queries trying to retrieve millions of rows from cassandra. 

When adding `limit '100'` to the CREATE SERVER cass  FOREIGN DATA WRAPPER multicorn OPTIONS or to the FOREIGN TABLE OPTIONS both result in 
`ERROR:  Error in python: NameError
DETAIL:  global name 'limit' is not defined
`
when executing a query against the foreign table. 

When listing the foreign server the keyword "limit" is in quotes while other keywords are not: 
`(wrapper 'cassandra-fdw.CassandraFDW', hosts '192.168.2.101', port '9042', username 'username', password 'password', "limit" '100')
`

The same for the foreign table:
` (columnfamily 'eventsc', keyspace 'stats', "limit" '100')
`
Am I'm doing something wrong or is "limit" currently just not supported?

**Comment by Sune357** [comment]
Hello, thank you for your report. This is a bug and I've fixed it in the last commit. Now the "limit" option works fine. Note, that this option may cause to unexpected behavior because it is written directly to the cassandra query, for example the sorting that occurs on the PostgreSQL side may give wrong results if the result set of your query is larger than the "limit" option.
